export const projectData = [
  {
    id: "1pro",
    name: "Backoffice",
    rate: 60,
    currency: "EUR",
    client: "solarisBank",
    themeColor: "#b32323",
  },
  {
    id: "2pro",
    name: "side project",
    rate: 0,
    currency: "",
    client: "Code Well Studio",
    themeColor: "#059481",
  },
  {
    id: "3pro",
    name: "PS5 Interface",
    rate: 90,
    currency: "USD",
    client: "Sony",
    themeColor: "#0a73bf",
  },
  {
    id: "4pro",
    name: "Daily app",
    rate: 0,
    currency: "",
    client: "Code Well Studio",
    themeColor: "#059481",
  },
];

export const eventsData = [
  {
    id: "1evt",
    description: "Amount and balance formatter fixes",
    hours: 7.5,
    date: "Fri Nov 03 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[0],
  },
  {
    id: "2evt",
    description: "Initialise app",
    hours: 2.5,
    date: "Fri Nov 03 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[1],
  },
  {
    id: "3evt",
    description: "Retrospective meeting and pairing",
    hours: 8,
    date: "Thu Nov 02 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[2],
  },
  {
    id: "4evt",
    description: "Pairing session",
    hours: 8,
    date: "Wed Nov 01 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[2],
  },
  {
    id: "5evt",
    description: "Pairing session",
    hours: 4,
    date: "Fri Oct 30 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[0],
  },
  {
    id: "6evt",
    description: "Quick sync with PO",
    hours: 1,
    date: "Fri Oct 30 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[2],
  },
  {
    id: "7evt",
    description: "Add routing",
    hours: 2,
    date: "Fri Oct 30 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[3],
  },
  {
    id: "8evt",
    description: "AWS testing configuration",
    hours: 2,
    date: "Fri Oct 30 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[1],
  },
  {
    id: "9evt",
    description: "Junior dev onboarding, code reviews",
    hours: 8,
    date: "Thu Oct 29 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[2],
  },
  {
    id: "10evt",
    description: "Sync with product about A/B testing",
    hours: 7,
    date: "Wed Oct 28 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[0],
  },
  {
    id: "11evt",
    description: "Research project ideas",
    hours: 2,
    date: "Wed Oct 28 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[1],
  },
  {
    id: "12evt",
    description: "Implement A/B testing",
    hours: 7,
    date: "Tue Oct 27 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[0],
  },
  {
    id: "13evt",
    description: "PS5 product page update",
    hours: 4,
    date: "Mon Oct 26 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[2],
  },
  {
    id: "14evt",
    description: "PS5 interface update",
    hours: 8,
    date: "Fri Oct 23 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[2],
  },
  {
    id: "15evt",
    description: "JS graphql learning",
    hours: 8,
    date: "Thu Oct 22 2020 12:00:00 GMT+0100 (Central European Standard Time)",
    project: projectData[1],
  },
];

export const activityData = [
  {
    id: "1act",
    date: eventsData[0].date,
    events: [{ ...eventsData[0] }, { ...eventsData[1] }],
  },
  {
    id: "2act",
    date: eventsData[2].date,
    events: [{ ...eventsData[2] }],
  },
  {
    id: "3act",
    date: eventsData[3].date,
    events: [{ ...eventsData[3] }],
  },
  {
    id: "4act",
    date: eventsData[4].date,
    events: [
      { ...eventsData[4] },
      { ...eventsData[5] },
      { ...eventsData[6] },
      { ...eventsData[7] },
    ],
  },
  {
    id: "5act",
    date: eventsData[8].date,
    events: [{ ...eventsData[8] }],
  },
  {
    id: "6act",
    date: eventsData[9].date,
    events: [{ ...eventsData[9] }, { ...eventsData[10] }],
  },
  {
    id: "7act",
    date: eventsData[11].date,
    events: [{ ...eventsData[11] }],
  },
  {
    id: "8act",
    date: eventsData[12].date,
    events: [{ ...eventsData[12] }],
  },
  {
    id: "9act",
    date: eventsData[13].date,
    events: [{ ...eventsData[13] }],
  },
  {
    id: "10act",
    date: eventsData[14].date,
    events: [{ ...eventsData[14] }],
  },
];
